### ISSUE TITLE
Expose clang_getNullCursor

### ISSUE THREAD

**Issue by qmfrederik** [GordenOu/Core.Clang#3]
I'm trying to detect whether a struct is a forward declaration or not.

[This article](https://joshpeterson.github.io/identifying-a-forward-declaration-with-libclang) says that you can do that using code like this:

```
static bool is_forward_declaration(CXCursor cursor)
{
  return clang_equalCursors(clang_getCursorDefinition(cursor),
                            clang_getNullCursor());
}
```

Unfortunately, libclang doesn't expose `getNullCursor` nor `equalCursors`.

Would it be possible to expose these methods, perhaps something like this:
- Add a static `Cursor.Zero` or `Cursor.NullCursor` property which woudl return `getNullCursor`
- Override the `Equals` method using `clang_equalCursors`?

**Comment by GordenOu** [comment]
Hi, have you check the Cursor.IsDefinition method? Please try the following visitor:

```CSharp
public class TestCursorVisitor : CursorVisitor
{
    protected override ChildVisitResult Visit(Cursor cursor, Cursor parent)
    {
        switch (cursor.Kind)
        {
            case CursorKind.StructDecl:
                Console.WriteLine(
                    $"{cursor.GetDisplayName()}.{nameof(cursor.IsDefinition)}: " 
                    + cursor.IsDefinition());
                break;
            default:
                break;
        }
        return ChildVisitResult.Recurse;
    }
}
```

By the way, please check the [source code](https://github.com/GordenOu/Core.Clang/blob/40c32c72c3305ad542ab9d3c3d9bd0cfd283e66f/Core.Clang/Cursor.cs#L77-L94) that I did override the Equals method using clang_equalCursors. And the null cursor will be automatically mapped to the null during [Cursor creation](https://github.com/GordenOu/Core.Clang/blob/40c32c72c3305ad542ab9d3c3d9bd0cfd283e66f/Core.Clang/Cursor.cs#L49-L57). So a solution corresponding to your mentioned article would be
```CSharp
static bool IsForwardDeclaration(Cursor cursor)
{
    return cursor.GetDefinition() == null;
}
```
